blueprints/login.py
from flask import Blueprint, request, session, redirect, render_template, url_for
from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017/")
db = client["ikawe"]
collection = db["dashboard"]

login_bp = Blueprint('login_bp', __name__)


@login_bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        users = db['users']
        user_logged = users.find_one({'username': username, 'password': password})

        if user_logged:
            user_logged_data = {
                'username': user_logged['username'],
                'name': user_logged['name'],
                'email': user_logged['email'],
                'rol': user_logged['rol']
            }
            session.clear()
            session['user_logged'] = user_logged_data
            return redirect(url_for('dashboard_bp.page_dashboard'))
        else:
            error_message = "User not valid"
            return render_template('index.html', error=error_message)
    return render_template('index.html')


@login_bp.route('/logout')
def logout():
    session.pop('user_logged', None)
    return redirect(url_for('main'))

templates/pages/login/login.html
<form method="POST" action="{{ url_for('login_bp.login') }}">
    {% if error %}
    <div class="row p-3">
        <div class="alert alert-danger" role="alert">
        {{ error }}
        </div>
    </div>
    {% endif %}
    <h1 class="display-5">Iniciar sesión</h1>
    <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" name="username" class="form-control" id="username" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" name="password" class="form-control" id="password">
    </div>
    <button type="submit" class="btn btn-lg racoon-btn-success">Log in</button>
</form>