blueprints/dashboard.py
import math
import pymongo
from bson import ObjectId
from flask import Blueprint, render_template, request, g, send_from_directory
from pymongo import MongoClient
from .decorators import require_login

dashboard_bp = Blueprint('dashboard_bp', __name__)

# MONGODB CONFIGURATION
client = MongoClient("mongodb://localhost:27017/")
db = client["ikawe"]
collection = db["books"]


@dashboard_bp.route('/', methods=['GET'])
@require_login
def page_dashboard():
    page = request.args.get('page', default=1, type=int)
    books_per_page = 25
    total_pages = math.ceil(g.total_books / books_per_page)
    skip = (page - 1) * books_per_page
    books = list(collection.find({})
                 .skip(skip)
                 .sort('saved_date', pymongo.DESCENDING)
                 .limit(books_per_page))

    for book in books:
        book['_id'] = str(book['_id'])
        book_cover = getCoverBook(book['cover_reference'])
        book['cover'] = book_cover['book_cover']
    return render_template('pages/dashboard/dashboard.html',
                           books=books,
                           page=page,
                           total_pages=total_pages)


def getCoverBook(book_id):
    cover_collection = db['books_cover']
    return cover_collection.find_one({"_id": ObjectId(book_id)})


@dashboard_bp.route('/detail/<string:book_id>', methods=['GET'])
@require_login
def page_book(book_id):
    book = collection.find_one({"_id": ObjectId(book_id)})
    book_cover = getCoverBook(book['cover_reference'])
    book['cover'] = book_cover['book_cover']
    if book:
        book['_id'] = str(book['_id'])
        return render_template('pages/dashboard/detail.html', book=book)
    else:
        return render_template('404.html')


@dashboard_bp.route('/detail/download/<filename>/<book_name>')
@require_login
def download_file(filename, book_name):
    custom_name = book_name.replace(' ', '_') + '.mobi'
    return send_from_directory('static/ebooks', filename, as_attachment=True, download_name=custom_name)

templates/pages/dashboard/dashboard.html
{% include "components/head.html" %}
{% include "components/navbar.html" %}

<div class="container-fluid ikake-jumbotron d-flex flex-column">
    <div class="container d-flex flex-grow-1 justify-content-center align-items-center">
        <h1 class="display-5">HOLA 👋.</h1>
    </div>
</div>

<div class="container-fluid racoon-library">
    <div class="container p-2 racoon-container-library">
        {% include "components/searcher.html" %}
        <div class="row p-4">
            {% if books %}
                {% for current_book in books %}
                    {% set book = current_book %}
                    {% include "components/book_card.html" %}
                {% endfor %}
            {% else %}
            <div class="text-center">
                <p class="text-muted">
                    <img src="{{ url_for('static', filename='images/logos/ikawe-shape.png') }}"
                        height="126" alt="">
                </p>
                <h2>Lo que estás buscando no está aqui...</h2>
            </div>
            {% endif %}
        </div>
        {% include "components/pagination.html" %}
    </div>
</div>

{% include "components/footer.html" %}

templates/pages/dashboard/detail.html
{% include "components/head.html" %}
{% include "components/navbar.html" %}

<div class="container-fluid  ikake-jumbotron"
     style="background-image: url('data:image/png;base64, {{ book.cover }}');
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center center;
            width: 100%;">
</div>
<div class="container-fluid ikake-jumbotron-title"  style="z-index: 1">
    <div class="container" style="z-index: 10">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a class="ikawe-btn-link-light" href="{{ url_for('main') | safe }}">Inicio</a>
            </li>
            <li class="breadcrumb-item">
                <a class="ikawe-btn-link-light" href="{{ url_for('dashboard_bp.page_dashboard') | safe }}">Librería</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">{{ book.book }}</li>
          </ol>
        </nav>
    </div>
    <div class="container text-center">
        <h1 class="display-5">{{book.book}}.</h1>
    </div>
</div>

<div class="container-fluid ikake-jumbotron-content">
    <div class="container p-2 racoon-container-library">
        {% if session['user_logged']['rol'] == 'admin' %}
            {% include "components/admin/admin-bar.html" %}
        {% endif %}
        <div class="row">
            <div class="col-12 p-4">
                <h1 class="border-bottom p-2">{{ book.book }}</h1>
                <div class="row">
                    <div class="col-9">
                        <p class="p-2">
                            <span class="badge ikawe-badge">{{ book.author }}</span>
                            <span class="badge ikawe-badge">{{ book.theme }}</span>
                            <span class="badge ikawe-badge">{{ book.year }}</span>
                        </p>
                        <p class="p-2">{{ book.summary }}</p>
                    </div>
                    <div class="col-3 text-center">
                        <p class="p-1">
                            {% if book.cover %}
                                <img src="data:image/png;base64, {{ book.cover }}" width="270" alt="{{ book.book }}">
                            {% else %}
                                <img src="{{ url_for('static', filename='images/no_cover.png') }}"
                                     width="270" class="" alt="{{ book.book }}">
                            {% endif %}
                        </p>
                        <p class="p-1">
                            <a href="{{ url_for('dashboard_bp.download_file', filename=book.ref_binary, book_name=book.book) }}"
                               class="btn btn-lg btn-block racoon-btn-success">Descargar libro (.mobi)</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% include "components/footer.html" %}