blueprints/dashboard.py
import math
import pymongo
from bson import ObjectId
from flask import Blueprint, render_template, request, g, send_from_directory
from pymongo import MongoClient
from .decorators import require_login

dashboard_bp = Blueprint('dashboard_bp', __name__)

# MONGODB CONFIGURATION
client = MongoClient("mongodb://localhost:27017/")
db = client["ikawe"]
collection = db["books"]


@dashboard_bp.route('/', methods=['GET'])
@require_login
def page_dashboard():
    page = request.args.get('page', default=1, type=int)
    books_per_page = 25
    total_pages = math.ceil(g.total_books / books_per_page)
    skip = (page - 1) * books_per_page
    books = list(collection.find({})
                 .skip(skip)
                 .sort('saved_date', pymongo.DESCENDING)
                 .limit(books_per_page))

    for book in books:
        book['_id'] = str(book['_id'])
        book_cover = getCoverBook(book['cover_reference'])
        book['cover'] = book_cover['book_cover']
    return render_template('pages/dashboard/dashboard.html',
                           books=books,
                           page=page,
                           total_pages=total_pages)


def getCoverBook(book_id):
    cover_collection = db['books_cover']
    return cover_collection.find_one({"_id": ObjectId(book_id)})


@dashboard_bp.route('/detail/<string:book_id>', methods=['GET'])
@require_login
def page_book(book_id):
    book = collection.find_one({"_id": ObjectId(book_id)})
    book_cover = getCoverBook(book['cover_reference'])
    book['cover'] = book_cover['book_cover']
    if book:
        book['_id'] = str(book['_id'])
        return render_template('pages/dashboard/detail.html', book=book)
    else:
        return render_template('404.html')


@dashboard_bp.route('/detail/download/<filename>/<book_name>')
@require_login
def download_file(filename, book_name):
    custom_name = book_name.replace(' ', '_') + '.mobi'
    return send_from_directory('static/ebooks', filename, as_attachment=True, download_name=custom_name)

blueprints/login.py
from flask import Blueprint, request, session, redirect, render_template, url_for
from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017/")
db = client["ikawe"]
collection = db["dashboard"]

login_bp = Blueprint('login_bp', __name__)


@login_bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        users = db['users']
        user_logged = users.find_one({'username': username, 'password': password})

        if user_logged:
            user_logged_data = {
                'username': user_logged['username'],
                'name': user_logged['name'],
                'email': user_logged['email'],
                'rol': user_logged['rol']
            }
            session.clear()
            session['user_logged'] = user_logged_data
            return redirect(url_for('dashboard_bp.page_dashboard'))
        else:
            error_message = "User not valid"
            return render_template('index.html', error=error_message)
    return render_template('index.html')


@login_bp.route('/logout')
def logout():
    session.pop('user_logged', None)
    return redirect(url_for('main'))

blueprints/profile.py
from flask import Blueprint, request, session, redirect, render_template, url_for
from .decorators import require_login

profile_bp = Blueprint('profile_bp', __name__)


@profile_bp.route('/profile', methods=['GET'])
@require_login
def page_profile():
    # TODO - Update Profile page
    return render_template('pages/profile/profile.html')

blueprints/search.py
from flask import Blueprint, render_template, request, g
from pymongo import MongoClient
from bson import ObjectId
from .decorators import require_login
import math, re

search_bp = Blueprint('search_bp', __name__)

# MONGODB CONFIGURATION
client = MongoClient("mongodb://localhost:27017/")
db = client["ikawe"]
collection = db["books"]


@search_bp.route('/search', methods=['GET', 'POST'])
@require_login
def search():
    if request.method == 'POST':
        keywords = request.form['keywords']

        regex_pattern = re.compile(f'.*{keywords}.*', re.IGNORECASE)
        search_result = collection.find({
            "$or": [
                {"book": {"$regex": regex_pattern}},
                {"author": {"$regex": regex_pattern}}
            ]
        })

        books = list(search_result)
        for book in books:
            book['_id'] = str(book['_id'])
            book_cover = getCoverBook(book['cover_reference'])
            book['cover'] = book_cover['book_cover']
        return render_template('pages/search/search-result.html',
                               books=books)


def getCoverBook(book_id):
    cover_collection = db['books_cover']
    return cover_collection.find_one({"_id": ObjectId(book_id)})

templates/components/book_card.html
<div class="card racoon-card p-0 m-2" style="width: 15rem;">
    <div class="racoon-card-header row">
        {% if book.cover %}
            <img src="data:image/png;base64, {{ book.cover }}"
                 class="racoon-img-responsive"
                 alt="{{ book.book }}">
        {% else %}
            <img src="{{ url_for('static', filename='images/no_cover.png') }}"
                 class="card-img-top" alt="{{ book.book }}">
        {% endif %}
    </div>
    <div class="card-body">
        <div class="racoon-card-title">
            <h5 class="card-title">{{ book.book }}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary"> {{ book.author }} </h6>
        </div>
        <div class="racoon-card-body">
            <p class="card-text">{{ book.summary | truncate_text(60) }}</p>
        </div>
    </div>
    <div class="card-footer d-grid gap-2 d-md-flex justify-content-md-center">
        <a class="btn racoon-btn-link"
           href="{{ url_for('dashboard_bp.page_book', book_id=book['_id']) | safe }}">
            Ver ficha </a>
        <a class="btn racoon-btn-success"
           href="{{ url_for('dashboard_bp.page_book', book_id=book['_id']) | safe }}">
            Descargar </a>
    </div>
</div>

templates/components/footer.html
        <div class="container">
            <footer class="py-3 my-4">
                <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                    <li class="nav-item">
                        <a href="{{ url_for('main')}}"
                           class="nav-link px-2 text-muted">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('dashboard_bp.page_dashboard')}}"
                           class="nav-link px-2 text-muted">Libreria</a>
                    </li>
                    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
                </ul>

                <p class="text-center text-muted">
                    <img src="{{ url_for('static', filename='images/logos/ikawe-shape.png') }}"
                        height="36" alt="">  © 2023 Ikawe, Inc</p>
            </footer>
        </div>
    </body>
</html>

templates/components/head.html
<!DOCTYPE html>
    <html>
        <head>
            <title>Ikawe</title>
            <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/logos/favicon.png') }}" />
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
            <!-- CUSTOM RACOON STYLE -->
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
        </head>
        <body>

templates/components/navbar.html
{% if custom_navbar_style %}
  <nav class="navbar navbar-expand-lg navbar-lightœ bg-light ikawe-navbar-light">
{% else %}
    <nav class="navbar navbar-expand-lg navbar-lightœ bg-light">
{% endif %}
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main') | safe }}">
      <img src="{{ url_for('static', filename='images/logos/ikawe-shape.png') }}"
         height="36" alt=""> Ìkàwé </a>
    {% if g.user %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main')}}">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('dashboard_bp.page_dashboard')}}">Biblioteca</a>
        </li>
      </ul>

      <img src="{{ url_for('static', filename='images/avatares/avatar_2.png') }}"
              height="32" alt="">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
             role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{ g.user.name }}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{{ url_for('profile_bp.page_profile') }}">Perfil</a></li>
            <li><a class="dropdown-item" href="#">Sugerencias</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{{ url_for('login_bp.logout')}}">Salir</a></li>
          </ul>
        </li>
      </ul>
    </div>
    {% endif %}
  </div>
</nav>

templates/components/pagination.html
<nav class="bg-light" aria-label="Ikawe navigation">
    <ul class="pagination justify-content-center p-4">
    {% if page > 1 %}
      <li class="page-item"><a class="page-link" href="?page=1">Primera</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ page - 1 }}">Atrás</a></li>
    {% endif %}

    {% for p in range(1, 10) %}
      <li class="page-item">
        <a href="?page={{ p }}"
           {% if p == page %} class="page-link active" {% else %} class="page-link" {% endif %}>
          {{ p }}
        </a>
      </li>
    {% endfor %}


    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">...</a>
    </li>

    {% for p in range(total_pages - 8 ,total_pages) %}
      <li class="page-item">
        <a href="?page={{ p }}"
           {% if p == page %} class="page-link active" {% else %} class="page-link" {% endif %}>
          {{ p }}
        </a>
      </li>
    {% endfor %}

    {% if page < total_pages %}
      <li class="page-item"><a class="page-link" href="?page={{ page + 1 }}">Siguiente</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ total_pages }}">Última</a></li>
    {% endif %}
    </ul>
</nav>

templates/components/searcher.html
<div class="bg-light p-3">
    <div class="container">
        <form method="POST" action="{{ url_for('search_bp.search') }}">
            <div class="row">
                <div class="col-11">
                    <input class="form-control" id="keywords" name="keywords" placeholder="Nombre de Libro, Autor...">
                </div>
                <div class="col-1">
                    <button type="submit" class="btn racoon-btn-success">Buscar</button>
                </div>
            </div>
        </form>
    </div>
</div>